required = [
    "github.com/emicklei/go-restful",
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/actuators",
    "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler",
    "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra",
    "github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators",
    "github.com/openshift/cluster-autoscaler-operator/pkg/apis",
    "github.com/openshift/api/config/v1",
    "github.com/onsi/ginkgo",
    "github.com/onsi/gomega",
    ]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.5"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.12.5"

[[override]]
  name = "github.com/openshift/cluster-api"
  revision = "eaaebe5a6fdf7fa96203bbdb9e2cf1165dd6ac1f"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.5"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.5"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  # version = "v0.1.8" # does not work, still pulls v.1.10 instead
  revision = "c63ebda0bf4be5f0a8abd4003e4ea546032545ba"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
 [[override]]
   name = "gopkg.in/fsnotify.v1"
   source = "https://github.com/fsnotify/fsnotify.git"
   version="v1.4.7"

[prune]
  go-tests = true

  [[prune.project]]
    name = "github.com/openshift/cluster-api-actuator-pkg"
    go-tests = false
