apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: machines.machine.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.providerStatus.instanceId
    name: Instance
    description: Instance ID of machine created in AWS
    type: string
  - JSONPath: .status.providerStatus.instanceState
    name: State
    description: State of the AWS instance
    type: string
  - JSONPath: .spec.providerSpec.value.instanceType
    name: Type
    description: Type of instance
    type: string
  - JSONPath: .spec.providerSpec.value.placement.region
    name: Region
    description: Region associated with machine
    type: string
  - JSONPath: .spec.providerSpec.value.placement.availabilityZone
    name: Zone
    description: Zone associated with machine
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: machine.openshift.io
  names:
    kind: Machine
    plural: machines
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            configSource:
              type: object
            metadata:
              type: object
            providerSpec:
              properties:
                value:
                  type: object
                valueFrom:
                  properties:
                    machineClass:
                      properties:
                        provider:
                          type: string
                      type: object
                  type: object
              type: object
            taints:
              items:
                type: object
              type: array
            versions:
              properties:
                controlPlane:
                  type: string
                kubelet:
                  type: string
              required:
              - kubelet
              type: object
          required:
          - providerSpec
        status:
          properties:
            addresses:
              items:
                type: object
              type: array
            conditions:
              items:
                type: object
              type: array
            errorMessage:
              type: string
            errorReason:
              type: string
            lastUpdated:
              format: date-time
              type: string
            nodeRef:
              type: object
            providerStatus:
              type: object
            versions:
              properties:
                controlPlane:
                  type: string
                kubelet:
                  type: string
              required:
              - kubelet
              type: object
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
