apiVersion: kustomize.config.k8s.io/v1beta1
images:
  - name: ""
    newName: ""
    newTag: ""
kind: Kustomization
patchesJson6902:
  - path: pull-policy-patch.yaml
    target:
      group: apps
      kind: Deployment
      name: controller-name
      namespace: namespace
      version: v1
  - path: pull-policy-patch.yaml
    target:
      group: apps
      kind: Deployment
      name: controller-name
      namespace: capi-webhook-system
      version: v1
resources:
  - source-manifest.yaml
