version: 2.1


jobs:
  build:
    machine:
      image: "ubuntu-2204:2022.10.2"
    environment:
      ALL_ARCH: "amd64 arm64"
      REGISTRY_QUAY: quay.io/giantswarm
      REGISTRY_CHINA: giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm
    steps:
      - checkout
      - run:
          name: Build the CAPI docker images
          command: |
            for registry in $REGISTRY_QUAY $REGISTRY_CHINA; do
              make docker-build-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$registry

              if [ -n "$CIRCLE_TAG" ]; then
                echo "Building tag $CIRCLE_TAG"
                make docker-build-all ALL_ARCH="$ALL_ARCH" TAG="$CIRCLE_TAG" REGISTRY=$registry
              fi
            done
      - run:
          name: Push to quay
          command: |
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io

            make docker-push-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$REGISTRY_QUAY

            if [ -n "$CIRCLE_TAG" ]; then
              echo "Pushing tag $CIRCLE_TAG"
              make docker-push-all ALL_ARCH="$ALL_ARCH" TAG="$CIRCLE_TAG" REGISTRY=$REGISTRY_QUAY
            fi

      - run:
          name: Push to aliyun
          command: |
            for n in $(seq 1 5); do
              (
                set -eu
                docker login --username $ALIYUN_USERNAME --password $ALIYUN_PASSWORD giantswarm-registry.cn-shanghai.cr.aliyuncs.com

                make docker-push-all ALL_ARCH="$ALL_ARCH" TAG=$CIRCLE_SHA1 REGISTRY=$REGISTRY_CHINA

                if [ -n "${CIRCLE_TAG:-}" ]; then
                  echo "Pushing tag $CIRCLE_TAG"
                  make docker-push-all ALL_ARCH="$ALL_ARCH" TAG="$CIRCLE_TAG" REGISTRY=$REGISTRY_CHINA
                fi
              ) || { echo "Failed attempt ${n}"; continue; }

              echo "Succeeded in attempt ${n}"
              exit 0
            done

            exit 1

workflows:
  version: 2
  build_and_update:
    jobs:
      - build:
          context:
            - architect
          filters:
            tags:
              only: /^v.*/
