version: 2.1


jobs:
  build:
    machine:
      image: "ubuntu-2004:202010-01"
    steps:
      - checkout
      - run:
          name: Build the CAPI docker images
          command: |
            make docker-build
      - run:
          name: Login to QUAY
          command: |
            docker login --username $QUAY_USERNAME --password $QUAY_PASSWORD quay.io
      - run:
          name: Push images
          command: |
            docker push quay.io/$CIRCLE_PROJECT_USERNAME/cluster-api-aws-controller:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_update:
    jobs:
      - build:
          context:
            - architect
