commonLabels:
  cluster.x-k8s.io/v1alpha3: v1alpha3
  cluster.x-k8s.io/v1alpha4: v1alpha4
  cluster.x-k8s.io/v1beta1: v1beta1_v1beta2

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/
resources:
- bases/infrastructure.cluster.x-k8s.io_awsmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_awsfargateprofiles.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml
- bases/infrastructure.cluster.x-k8s.io_awsclustertemplates.yaml
- bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanes.yaml
- bases/controlplane.cluster.x-k8s.io_awsmanagedcontrolplanetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmanagedclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_awsmanagedclustertemplates.yaml
- bases/bootstrap.cluster.x-k8s.io_eksconfigs.yaml
- bases/bootstrap.cluster.x-k8s.io_eksconfigtemplates.yaml
- bases/controlplane.cluster.x-k8s.io_rosacontrolplanes.yaml
- bases/infrastructure.cluster.x-k8s.io_rosaclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_rosamachinepools.yaml
- bases/infrastructure.cluster.x-k8s.io_rosaroleconfigs.yaml
- bases/infrastructure.cluster.x-k8s.io_rosanetworks.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_awsmachines.yaml
- patches/webhook_in_awsclusters.yaml
- patches/webhook_in_awsmachinetemplates.yaml
- patches/webhook_in_awsclustercontrolleridentities.yaml
- patches/webhook_in_awsclusterroleidentities.yaml
- patches/webhook_in_awsclustertemplates.yaml
- patches/webhook_in_awsmanagedcontrolplanes.yaml
- patches/webhook_in_awsmanagedcontrolplanetemplates.yaml
- patches/webhook_in_eksconfigs.yaml
- patches/webhook_in_eksconfigtemplates.yaml
  # +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_awsmachines.yaml
- patches/cainjection_in_awsclusters.yaml
- patches/cainjection_in_awsmachinetemplates.yaml
- patches/cainjection_in_awsclustercontrolleridentities.yaml
- patches/cainjection_in_awsclusterroleidentities.yaml
- patches/cainjection_in_awsclustertemplates.yaml
- patches/cainjection_in_awsmanagedcontrolplanes.yaml
- patches/cainjection_in_awsmanagedcontrolplanetemplates.yaml
- patches/cainjection_in_awsmanagedclusters.yaml
- patches/cainjection_in_awsmanagedclustertemplates.yaml
- patches/cainjection_in_eksconfigs.yaml
- patches/cainjection_in_eksconfigtemplates.yaml
- patches/cainjection_in_rosaroleconfigs.yaml
- patches/cainjection_in_rosanetworks.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# [LABEL] To enable label, uncomment all the sections with [LABEL] prefix.
# patches here are for adding the label to each global identity CRDs
- patches/label_in_awsclustercontrolleridentities.yaml
- patches/label_in_awsclusterroleidentities.yaml
- patches/label_in_awsclusterstaticidentities.yaml

# +kubebuilder:scaffold:crdkustomizelabelpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
