# Copyright 2021 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
settings:
  name: cluster-api-provider-aws
  min_similarity: 0.72
  repos:
    - https://github.com/kubernetes-sigs/cluster-api-provider-aws

  member-roles:
    # Automatically add members from these roles (exclude default of "member")
    # See https://developer.github.com/v4/enum/commentauthorassociation/
    - collaborator
    - owner
  members:
    - randomvariable
    - sedefsavas
    - richardcase

collections:
  - id: daily-triage
    name: Daily Triage
    dedup: true
    description: >
      triage-onduty zeroes out this queue once a day. Prioritize:

       * Keeping an open dialog with our users
       * Initial prioritization (does not have to be perfect)
    rules:
      # Don't leave code reviews hanging
      - pr-approved-stale
      - pr-reviewable
      # SLO violations
      - issue-needs-priority-slo
      - issue-needs-comment-slo
      - issue-important-slo
      - issue-longterm-slo
      # missing initial feedback
      - issue-needs-kind
      - issue-needs-priority
      - issue-needs-comment
      # reprioritize
      - issue-new-with-reactions
      - issue-new-with-many-commenters
      # Don't forget our users
      - issue-updated-needs-info
      - issue-updated-has-question

  - id: weekly
    name: Weekly Triage
    dedup: true
    description: >
      Once a week, we meet up to address loose ends. Prioritize:

       * Keeping an open dialog with our users
       * Raising the priority for hot issues
    rules:
      - discuss
      # Issues needing closure
      - issue-stale-needs-info
      - issue-stale-support
      - lifecycle-rotten
      # People with questions
      - issue-has-question
      - issue-updated-support
      # SLO
      - issue-near-important-slo
      - issue-near-longterm-slo
      # PR's needing closure
      - pr-reviewable-older
      - pr-approved-stale
      - pr-unapproved-stale
      # Issues needing reprioritization
      - many-reactions
      - many-commenters
      - issue-zombies

  - id: scrub
    name: Bi-Monthly Scrub
    dedup: true
    description: >
      Once every two months, we look for stale issues and de-duplicate. Prioritize:

       * De-duplication
       * Keeping the bug queue relevant
       * Making tough decisions about long-standing requests
    rules:
      - lifecycle-stale
      - features-recv
      - features-old
      - bugs-recv
      - bugs-old
      - other-recv
      - other-old

  - id: milestone
    name: In Milestone
    description: >
      A Kanban visualization of milestones, showing the flow of issues through each stage.

        * Unassigned issues represent available work
        * >3 issues assigned to the same person within a stage signifies a bottleneck ðŸŒŠ
    display: kanban
    overflow: 3
    dedup: true
    rules:
      - milestone-not-started
      - milestone-assignee-updated
      - milestone-pr-needs-review
      - milestone-pr-needs-work
      - milestone-pr-needs-merge
      - milestone-recently-closed

  - id: tests
    name: Broken tests
    description: Failing tests, flaky tests, and other improvements
    rules:
      - failing-tests
      - flaky-tests
      - other-testing

  - id: important
    name: Important
    description: >
      Items labeled as priority/important-soon or priority/critical-urgent.
    overflow: 3
    dedup: true
    rules:
      - important-not-milestoned
      - important-milestoned
      - important-assignee-updated
      - important-pr-needs-review
      - important-pr-needs-work
      - important-pr-needs-merge
      - important-recently-closed

  - id: similar
    name: Similar
    description: Items which appear similar to one other. Review for duplicates or vague titles.
    rules:
      - similar-prs
      - similar-issues

  - id: __open__
    name: All open PR's and Issues that should be considered for repository stats (hidden)
    used_for_statistics: true
    hidden: true
    rules:
      - open-prs
      - open-issues

  - id: __velocity__
    name: issues to include in velocity metrics
    used_for_statistics: true
    hidden: true
    rules:
      - closed-milestone-issues

rules:
  ### Milestone Kanban ###
  milestone-not-started:
    name: "Not started"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "!assignee-updated"
      - tag: "!(assignee-open-pr|assignee-closed-pr)"
  milestone-assignee-updated:
    name: "In Progress"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "assignee-updated"
      - tag: "!(pr-changes-requested|pr-reviewer-comment|pr-unreviewed|pr-new-commits|pr-approved|pr-changes-requested)"
  milestone-pr-needs-work:
    name: "PR needs work"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-changes-requested|pr-reviewer-comment)"
  milestone-pr-needs-review:
    name: "PR needs Review"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-unreviewed|pr-new-commits)"
  milestone-pr-needs-merge:
    name: "PR needs Merge"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-approved|pr-approved-but-pushed)"
  milestone-recently-closed:
    name: "Finish Line"
    type: issue
    filters:
      - tag: open-milestone
      - state: closed
      - updated: -30d

  ### Important Kanban ###
  important-not-milestoned:
    name: "Not in milestone"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "!open-milestone"
      - tag: "!assignee-updated"
      - tag: "!(assignee-open-pr|assignee-closed-pr)"
  important-milestoned:
    name: "In Milestone"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: open-milestone
      - tag: "assignee-updated"
      - tag: "!(pr-changes-requested|pr-reviewer-comment|pr-unreviewed|pr-new-commits|pr-approved|pr-changes-requested)"
  important-assignee-updated:
    name: "In Progress"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "assignee-updated"
      - tag: "!(pr-changes-requested|pr-reviewer-comment|pr-unreviewed|pr-new-commits|pr-approved|pr-changes-requested)"
  important-pr-needs-work:
    name: "PR needs work"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "(pr-changes-requested|pr-reviewer-comment)"
  important-pr-needs-review:
    name: "PR needs Review"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "(pr-unreviewed|pr-new-commits)"
  important-pr-needs-merge:
    name: "PR needs Merge"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - tag: "(pr-approved|pr-approved-but-pushed)"
  important-recently-closed:
    name: "Recently closed"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - state: closed
      - updated: -30d

  ### Daily Triage ####
  # SLO violations
  issue-needs-priority-slo:
    name: "Unprioritized issues older than 5 days"
    resolution: "Add a priority/ or kind/support label"
    type: issue
    filters:
      - label: "!priority/.*"
      - label: "!kind/support"
      - created: +5d

  issue-needs-comment-slo:
    name: "Uncommented older than 5 days"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: "!commented"
      - tag: "recv"
      - created: +5d

  issue-important-slo:
    name: "Important soon, but no updates in 60 days -- exceeds limit"
    resolution: "Downgrade to important-longterm"
    type: issue
    filters:
      - label: "priority/important-soon"
      - updated: +60d

  issue-longterm-slo:
    name: "Important longterm, but no updates in 120 days -- exceeds limit"
    resolution: "Downgrade to backlog"
    type: issue
    filters:
      - label: "priority/important-longterm"
      - updated: +120d

  # Don't leave code reviews hanging
  pr-reviewable:
    name: "Pull Requests: Review Ready"
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "!cncf-cla: no"
      - tag: "!changes-requested"
      - tag: "!send"
      # Temporarily workaround inability to track PR eligibility
      - updated: +1d

  pr-reviewable-older:
    name: "Pull Requests: Review Ready"
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "!cncf-cla: no"
      - tag: "!changes-requested"
      - tag: "!send"
      - updated: +2d

  # Issues missing initial feedback
  issue-needs-kind:
    name: "Unkinded Issues"
    resolution: "Add a kind/ label"
    type: issue
    filters:
      - label: "!kind/.*"
      - label: "!kind/support"

  issue-needs-priority:
    name: "Unprioritized Issues within SLO"
    resolution: "Add a priority/ or kind/support label"
    type: issue
    filters:
      - label: "!priority/.*"
      - label: "!kind/support"
      # avoid duplicating unkinded issues
      - label: "triage|kind"
      - created: -5d

  issue-needs-comment:
    name: "Uncommented Issues within SLO"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: "!commented"
      - tag: "recv"
      - created: -5d

  # Issues that may need reprioritized
  issue-new-with-reactions:
    name: "New, has multiple reactions, but not important-soon"
    resolution: "Check if issue should be prioritized as important-soon"
    type: issue
    filters:
      - reactions: ">2"
      - created: -10d
      - tag: "!send"
      - label: "!priority/important-soon"

  issue-new-with-many-commenters:
    name: "New, has multiple commenters, but not important-soon"
    resolution: "Check if issue should be prioritized as important-soon"
    type: issue
    filters:
      - commenters: ">3"
      - created: -10d
      - tag: "!send"
      - label: "!priority/important-soon"

  # Don't forget our users
  issue-updated-needs-info:
    name: "needs information, has update"
    resolution: "Comment and remove triage/needs-information tag"
    type: issue
    filters:
      - label: triage/needs-information
      - tag: recv

  issue-updated-has-question:
    name: "Recently updated issue has a question"
    resolution: "Add an answer"
    type: issue
    filters:
      - tag: recv-q
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +3d
      - updated: -7d

  ####### Weekly Triage #########
  discuss:
    name: "Items for discussion"
    resolution: "Discuss and remove label"
    filters:
      - label: triage/discuss
      - state: "all"

  # SLO nearing
  issue-near-important-slo:
    name: "Important soon, but no updates in 40 days -- nearing limit"
    resolution: "Downgrade to important-longterm"
    type: issue
    filters:
      - label: "priority/important-soon|priority/critical-urgent"
      - updated: +40d

  issue-near-longterm-slo:
    name: "Important longterm, but no updates in 110 days -- nearing limit"
    resolution: "Downgrade to backlog"
    type: issue
    filters:
      - label: "priority/important-longterm"
      - updated: +110d

  # issues needing reprioritization
  many-reactions:
    name: "many reactions, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    filters:
      - reactions: ">3"
      - reactions-per-month: ">0.75"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"

  many-commenters:
    name: "many commenters, low priority"
    resolution: "Upgrade to priority-soon, priority-longterm, or longterm-support"
    type: issue
    filters:
      - commenters: ">2"
      - commenters-per-month: ">1.9"
      - created: "+30d"
      - label: "!priority/important-soon"
      - label: "!priority/important-longterm"
      - label: "!long-term-support"
      - responded: "+30d"

  issue-zombies:
    name: "Screaming into the void"
    resolution: "Reopen, or ask folks to open a new issue"
    type: issue
    filters:
      - state: closed
      - updated: -7d
      - tag: recv
      - comments-while-closed: ">1"

  # Issues needing closure
  issue-stale-needs-info:
    name: "Needs information for over 2 weeks"
    resolution: "Close or remove triage/needs-information label"
    type: issue
    filters:
      - label: triage/needs-information
      - updated: +13d

  issue-stale-support:
    name: "Support request over 30 days old"
    resolution: "Close, or add to triage/long-term-support"
    type: issue
    filters:
      - label: kind/support
      - label: "!long-term-support"
      - updated: +29d

  lifecycle-rotten:
    name: "Issues nearing expiration"
    resolution: "Close or label as frozen"
    filters:
      - label: lifecycle/rotten

  # PR's needing closure
  pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "approved"
      - updated: +5d

  pr-unapproved-stale:
    name: "Pull Requests: Stale"
    resolution: "Add comment and/or close PR"
    type: pull_request
    filters:
      - created: +20d
      - updated: +5d

  # People with questions
  issue-has-question:
    name: "Overdue answers for a question"
    resolution: "Add a comment"
    type: issue
    filters:
      - tag: recv-q
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  issue-updated-support:
    name: "Updated support requests"
    resolution: "Move out of support, or add a comment"
    type: issue
    filters:
      - tag: recv
      - label: "!triage/needs-information"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +6d

  ## Bug Scrub ##
  bugs-recv:
    name: "Bugs that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +45d
      - created: +45d
      - label: "kind/bug"

  features-recv:
    name: "Features that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +60d
      - created: +30d
      - label: "kind/feature"

  other-recv:
    name: "Items that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +30d
      - label: "!kind/feature"
      - label: "!kind/bug"
      - label: "!kind/support"

  features-old:
    name: "Features that have not been commented on within 90 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +90d
      - created: +90d
      - label: "kind/feature"

  bugs-old:
    name: "Bugs that have not been commented on within 60 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - label: "kind/bug"
      - responded: +60d
      - created: +60d
      - label: "!priority/awaiting-evidence"

  other-old:
    name: "Items that have not been commented on within 60 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +60d
      - created: +60d
      - label: "!kind/feature"
      - label: "!kind/bug"
      - label: "!kind/support"
      - label: "!priority/awaiting-evidence"

  lifecycle-stale:
    name: "Issues nearing expiration"
    resolution: "Close or label as frozen"
    filters:
      - label: lifecycle/stale

  ## Similar
  similar-prs:
    name: "Similar Pull Requests"
    type: pull_request
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  similar-issues:
    name: "Similar Issues"
    type: issue
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  ## Tests
  failing-tests:
    name: "Tests that fail 100% of the time"
    resolution: "Research and resolve"
    type: issue
    filters:
      - label: "kind/failing-test"

  flaky-tests:
    name: "Tests that fail some of the time"
    resolution: "Research and resolve"
    type: issue
    filters:
      - label: "kind/flake"
      - label: "!kind/failing-test"

  other-testing:
    name: "Other testing related issues"
    resolution: "Research and resolve"
    type: issue
    filters:
      - label: "area/testing"
      - label: "!kind/flake"
      - label: "!kind/failing"

  # for statistics generation
  open-issues:
    name: "Open Issues"
    type: issue

  open-prs:
    name: "Open PRs"
    type: pull_request

  closed-milestone-issues:
    name: "Recently closed milestone issues"
    type: issue
    filters:
      - state: closed
      - closed: -90d
      - milestone: ".*"
      - label: "!triage/duplicate"
