---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: rosamachinepools.infrastructure.cluster.x-k8s.io
spec:
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: ROSAMachinePool
    listKind: ROSAMachinePoolList
    plural: rosamachinepools
    shortNames:
    - rosamp
    singular: rosamachinepool
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: MachinePool ready status
      jsonPath: .status.ready
      name: Ready
      type: string
    - description: Number of replicas
      jsonPath: .status.replicas
      name: Replicas
      type: integer
    name: v1beta2
    schema:
      openAPIV3Schema:
        description: ROSAMachinePool is the Schema for the rosamachinepools API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RosaMachinePoolSpec defines the desired state of RosaMachinePool.
            properties:
              additionalSecurityGroups:
                description: AdditionalSecurityGroups is an optional set of security
                  groups to associate with all node instances of the machine pool.
                items:
                  type: string
                type: array
              autoRepair:
                default: false
                description: AutoRepair specifies whether health checks should be
                  enabled for machines in the NodePool. The default is false.
                type: boolean
              autoscaling:
                description: Autoscaling specifies auto scaling behaviour for this
                  MachinePool. required if Replicas is not configured
                properties:
                  maxReplicas:
                    minimum: 1
                    type: integer
                  minReplicas:
                    minimum: 1
                    type: integer
                type: object
              availabilityZone:
                description: AvailabilityZone is an optinal field specifying the availability
                  zone where instances of this machine pool should run For Multi-AZ
                  clusters, you can create a machine pool in a Single-AZ of your choice.
                type: string
              instanceType:
                description: InstanceType specifies the AWS instance type
                type: string
              labels:
                additionalProperties:
                  type: string
                description: Labels specifies labels for the Kubernetes node objects
                type: object
              nodeDrainGracePeriod:
                description: NodeDrainGracePeriod is grace period for how long Pod
                  Disruption Budget-protected workloads will be respected during upgrades.
                  After this grace period, any workloads protected by Pod Disruption
                  Budgets that have not been successfully drained from a node will
                  be forcibly evicted. The nodeDrainGracePeriod can be defined in
                  minutes, hours ex; 30m, 10h. The max value can be assigned is 10080m|168h
                  (1 week).
                pattern: ^(([0-9])+[m|h])$
                type: string
              nodePoolName:
                description: NodePoolName specifies the name of the nodepool in Rosa
                  must be a valid DNS-1035 label, so it must consist of lower case
                  alphanumeric and have a max length of 15 characters.
                maxLength: 15
                pattern: ^[a-z]([-a-z0-9]*[a-z0-9])?$
                type: string
                x-kubernetes-validations:
                - message: nodepoolName is immutable
                  rule: self == oldSelf
              providerIDList:
                description: ProviderIDList contain a ProviderID for each machine
                  instance that's currently managed by this machine pool.
                items:
                  type: string
                type: array
              subnet:
                type: string
                x-kubernetes-validations:
                - message: subnet is immutable
                  rule: self == oldSelf
              taints:
                description: Taints specifies the taints to apply to the nodes of
                  the machine pool
                items:
                  description: RosaTaint represents a taint to be applied to a node.
                  properties:
                    effect:
                      description: The effect of the taint on pods that do not tolerate
                        the taint. Valid effects are NoSchedule, PreferNoSchedule
                        and NoExecute.
                      enum:
                      - NoSchedule
                      - PreferNoSchedule
                      - NoExecute
                      type: string
                    key:
                      description: The taint key to be applied to a node.
                      type: string
                    value:
                      description: The taint value corresponding to the taint key.
                      pattern: ^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?$
                      type: string
                  required:
                  - effect
                  - key
                  type: object
                type: array
              tuningConfigs:
                description: TuningConfigs specifies the names of the tuning configs
                  to be applied to this MachinePool. Tuning configs must already exist.
                items:
                  type: string
                type: array
              version:
                description: Version specifies the OpenShift version of the nodes
                  associated with this machinepool. ROSAControlPlane version is used
                  if not set.
                type: string
            required:
            - instanceType
            - nodePoolName
            type: object
          status:
            description: RosaMachinePoolStatus defines the observed state of RosaMachinePool.
            properties:
              conditions:
                description: Conditions defines current service state of the managed
                  machine pool
                items:
                  description: Condition defines an observation of a Cluster API resource
                    operational state.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    severity:
                      description: Severity provides an explicit classification of
                        Reason code, so the users or machines can immediately understand
                        the current situation and act accordingly. The Severity field
                        MUST be set only when Status=False.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              failureMessage:
                description: "FailureMessage will be set in the event that there is
                  a terminal problem reconciling the state and will be set to a descriptive
                  error message. \n This field should not be set for transitive errors
                  that a controller faces that are expected to be fixed automatically
                  over time (like service outages), but instead indicate that something
                  is fundamentally wrong with the spec or the configuration of the
                  controller, and that manual intervention is required."
                type: string
              id:
                description: ID is the ID given by ROSA.
                type: string
              ready:
                default: false
                description: Ready denotes that the RosaMachinePool nodepool has joined
                  the cluster
                type: boolean
              replicas:
                description: Replicas is the most recently observed number of replicas.
                format: int32
                type: integer
            required:
            - ready
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
